"use strict";

const assert=require("assert");
const fs=require("fs");
const os=require("os");
const path=require("path");
const {spawnSync}=require("child_process");
const {buildSample}=require("../scripts/build_public_execution_proof_sample.cjs");
const {verifyExecutionProofBundle}=require("../scripts/execution_proof_bundle.cjs");

{
  const bundle=buildSample();
  const verified=verifyExecutionProofBundle(bundle);
  assert.equal(verified.valid,true);
  assert.equal(verified.physical_truth_verified,true);
  assert.equal(verified.physical_completion_verified,true);

  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"flythink-public-proof-"));
  const file=path.join(dir,"sample.json");
  fs.writeFileSync(file,JSON.stringify(bundle,null,2)+"\n");

  const cli=spawnSync(
    process.execPath,
    [
      path.join(__dirname,"..","scripts","verify_execution_proof_bundle_cli.cjs"),
      file
    ],
    {encoding:"utf8"}
  );
  assert.equal(cli.status,0);
  const row=JSON.parse(cli.stdout.trim());
  assert.equal(row.verdict,"VERIFIED");
  assert.equal(row.physical_truth_verified,true);
  assert.equal(row.physical_completion_verified,true);
}

console.log(JSON.stringify({
  ok:true,
  contract:"public proof quickstart is generated by canonical builders and verified by the canonical CLI with physical completion visible"
}));
