import json,sys,unittest
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'scripts'))
from dialogue_delta_corpus import corpus,empty_state,apply,delta,NONE
from train_flywire_delta import clause_features,normalize_aliases,TEXT_DIM,resolve,pack
import torch
from infer_flywire_delta import authorized

class DeltaContract(unittest.TestCase):
 def test_reference_resolution_does_not_overwrite_a_new_slot(self):
  before=apply(empty_state(),delta('add',[2],[2],'explicit'))
  rows=[{'turns':[{'text':'把它改成70%','before':before,'delta':delta('revise',[3],[4],'focus_coreference')}]}]
  _,gold,examples=pack(rows)
  result=resolve(gold,examples)
  torch.testing.assert_close(result,gold)
 def test_template_sets_and_sealed_cases_exist(self):
  data=corpus();self.assertEqual(len(data['train']),900);self.assertEqual(len(data['test']),180);self.assertEqual(len(data['sealed']),6)
 def test_all_multi_separators_feed_the_second_target_path(self):
  for text in ('打开客厅灯；关闭主卧窗户','打开客厅灯，同时关闭主卧窗户','一边打开客厅灯，一边关闭主卧窗户','客厅窗户开启，书房窗户关闭'):
   x=clause_features(text);self.assertGreater(float(x[TEXT_DIM*2:TEXT_DIM*3].abs().sum()),0,text)
 def test_alias_channel_normalizes_unseen_surface_forms(self):
  self.assertEqual(normalize_aliases('客厅里的灯关上'),normalize_aliases('客厅的灯关掉'))
  self.assertEqual(normalize_aliases('主卧窗户开到70%'),normalize_aliases('主卧窗户调整为70%'))
 def test_destructive_gate_requires_explicit_scope(self):
  clear={'op':'clear'};retract={'op':'retract'}
  self.assertFalse(authorized(clear,'撤销刚才那项')[0])
  self.assertTrue(authorized(clear,'撤销当前全部意图')[0])
  self.assertFalse(authorized(retract,'客厅灯打开')[0])
  self.assertTrue(authorized(retract,'删除客厅灯这项设置')[0])
 def test_delta_does_not_replace_unmentioned_state(self):
  s=apply(empty_state(),delta('add',[0,6],[2,2],'explicit'))
  retained=apply(s,delta('retain'));self.assertEqual(retained,s)
  revised=apply(s,delta('revise',[6],[1],'focus_coreference'));self.assertEqual(revised['values'][0],2);self.assertEqual(revised['values'][6],1)
 def test_scoped_retraction_and_full_clear_differ(self):
  s=apply(empty_state(),delta('add',[0,6],[2,2],'explicit'));s=apply(s,delta('retract',[6],[],'explicit_named'))
  self.assertEqual(s['values'][0],2);self.assertEqual(s['values'][6],0);self.assertEqual(apply(s,delta('clear'))['values'],[0]*12)
 def test_report_meets_bounded_80_percent_gate(self):
  path=Path('artifacts/flywire-delta-v14/report.json')
  if not path.exists():self.skipTest('train artifact is generated by the FlyWire workflow')
  m=json.loads(path.read_text())['runs']['real']['heldout_templates']
  required=['operation_accuracy','reference_accuracy','target_accuracy','room_accuracy','object_accuracy','property_accuracy','value_accuracy','delta_exact','coreference_target_accuracy','retraction_delta_exact','multi_intent_exact','ood_route_accuracy','count_accuracy']
  self.assertTrue(all(m[k]>=.8 for k in required),{k:m[k] for k in required if m[k]<.8})

if __name__=='__main__':unittest.main()
