"""Post-v14 freeze suite. Never import this module from training code."""
import copy
from dialogue_delta_corpus import empty_state,apply,delta

SPECS=[
 ('v5-a',[
  ('麻烦开启书房的窗户',delta('add',[10],[2],'explicit')),
  ('将这个窗口改到70%',delta('revise',[11],[4],'focus_coreference')),
  ('当前要求保持原状',delta('retain')),
  ('撤除书房窗户这条设置',delta('retract',[11],[],'explicit_named')),
  ('替我生成一份露营装备清单',delta('ood'))]),
 ('v5-b',[
  ('关闭客厅灯，同时打开主卧窗户',delta('add',[0,6],[1,2],'explicit')),
  ('把后一条改为关闭',delta('revise',[6],[1],'focus_coreference')),
  ('暂停刚才的窗口控制',delta('pause',[6],[],'focus_coreference')),
  ('恢复被暂停的控制',delta('resume',[6],[],'focus_coreference')),
  ('撤回全部家居控制意图',delta('clear'))]),
 ('v5-c',[
  ('客厅窗户设为30%',delta('add',[3],[3],'explicit')),
  ('书房灯设为70%',delta('add',[9],[4],'explicit')),
  ('请将客厅窗户变更为70%',delta('revise',[3],[4],'explicit_named')),
  ('删除书房灯对应设置',delta('retract',[9],[],'explicit_named')),
  ('剩余任务继续有效',delta('retain'))]),
 ('v5-d',[
  ('主卧灯打开，另外客厅窗户关闭',delta('add',[4,2],[2,1],'explicit')),
  ('上一项窗户控制改为打开',delta('revise',[2],[2],'focus_coreference')),
  ('先把该任务挂起',delta('pause',[2],[],'focus_coreference')),
  ('重新恢复这个任务',delta('resume',[2],[],'focus_coreference')),
  ('帮我生成一份早餐菜单',delta('ood'))]),
 ('v5-e',[
  ('书房窗户设置为70%；主卧灯设置为30%',delta('add',[11,5],[4,3],'explicit')),
  ('将最后的灯光调高到70%',delta('revise',[5],[4],'focus_coreference')),
  ('主卧灯的要求取消',delta('retract',[5],[],'explicit_named')),
  ('书房窗口任务维持不动',delta('retain')),
  ('清空全部任务',delta('clear'))]),
 ('v5-f',[
  ('打开客厅灯',delta('add',[0],[2],'explicit')),
  ('不对，那个灯应当关闭',delta('revise',[0],[1],'focus_coreference')),
  ('接着让主卧窗户达到30%',delta('add',[7],[3],'explicit')),
  ('刚提到的任务暂时中止',delta('pause',[7],[],'focus_coreference')),
  ('接续此前中止的任务',delta('resume',[7],[],'focus_coreference'))]),
 ('v5-g',[
  ('主卧的窗户关闭，并且书房的灯开启',delta('add',[6,8],[1,2],'explicit')),
  ('把书房灯更改为关闭',delta('revise',[8],[1],'explicit_named')),
  ('主卧窗口那项不用执行了',delta('retract',[6],[],'explicit_named')),
  ('其它控制保持现状',delta('retain')),
  ('写出一段科普视频提纲',delta('ood'))]),
 ('v5-h',[
  ('客厅灯调整到70%',delta('add',[1],[4],'explicit')),
  ('请暂停当前亮度任务',delta('pause',[1],[],'focus_coreference')),
  ('分析这份商业计划的风险',delta('ood')),
  ('继续先前暂停的亮度任务',delta('resume',[1],[],'focus_coreference')),
  ('然后把亮度降至30%',delta('revise',[1],[3],'focus_coreference'))]),
 ('v5-i',[
  ('客厅窗户开启，书房窗户关闭',delta('add',[2,10],[2,1],'explicit')),
  ('最后一个窗口改为开启',delta('revise',[10],[2],'focus_coreference')),
  ('去掉客厅窗户这条意图',delta('retract',[2],[],'explicit_named')),
  ('当前剩下的照常执行',delta('retain')),
  ('把一切控制任务全部取消',delta('clear'))]),
 ('v5-j',[
  ('主卧灯设置为30%',delta('add',[5],[3],'explicit')),
  ('书房灯打开',delta('add',[8],[2],'explicit')),
  ('客厅窗户设置为70%',delta('add',[3],[4],'explicit')),
  ('撤销书房灯这一要求',delta('retract',[8],[],'explicit_named')),
  ('没有其它改动',delta('retain'))]),
 ('v5-k',[
  ('关闭书房灯，并且把客厅灯设到30%',delta('add',[8,1],[1,3],'explicit')),
  ('后面的亮度换为70%',delta('revise',[1],[4],'focus_coreference')),
  ('暂停该亮度设置',delta('pause',[1],[],'focus_coreference')),
  ('恢复刚才的亮度设置',delta('resume',[1],[],'focus_coreference')),
  ('全部控制意图作废',delta('clear'))]),
 ('v5-l',[
  ('书房窗户打开',delta('add',[10],[2],'explicit')),
  ('替我列出本周健身安排',delta('ood')),
  ('窗口控制仍按原计划',delta('retain')),
  ('把它切换为关闭',delta('revise',[10],[1],'focus_coreference')),
  ('取消刚才那项窗口控制',delta('retract',[10],[],'focus_coreference'))]),
 ('v5-m',[
  ('主卧窗户设到70%，同时客厅灯设到30%',delta('add',[7,1],[4,3],'explicit')),
  ('前述灯光改为70%',delta('revise',[1],[4],'focus_coreference')),
  ('删除主卧窗户的设置',delta('retract',[7],[],'explicit_named')),
  ('已保留的灯光不要调整',delta('retain')),
  ('构思一个儿童故事大纲',delta('ood'))]),
 ('v5-n',[
  ('客厅灯打开',delta('add',[0],[2],'explicit')),
  ('主卧灯打开',delta('add',[4],[2],'explicit')),
  ('书房灯关闭',delta('add',[8],[1],'explicit')),
  ('主卧灯改作关闭',delta('revise',[4],[1],'explicit_named')),
  ('撤掉客厅灯要求',delta('retract',[0],[],'explicit_named'))]),
 ('v5-o',[
  ('把客厅窗户关上',delta('add',[2],[1],'explicit')),
  ('等一下，上一项还是打开',delta('revise',[2],[2],'focus_coreference')),
  ('冻结当前指令',delta('pause',[2],[],'focus_coreference')),
  ('恢复冻结指令',delta('resume',[2],[],'focus_coreference')),
  ('删除目前所有意图',delta('clear'))]),
 ('v5-p',[
  ('主卧灯打开，不，改为关闭',delta('add',[4],[1],'explicit')),
  ('书房窗户调整到30%',delta('add',[11],[3],'explicit')),
  ('现在把这个数值换成70%',delta('revise',[11],[4],'focus_coreference')),
  ('两项控制暂时都保留',delta('retain')),
  ('全部撤销',delta('clear'))]),
]

def blind_v5():
 out=[]
 for name,items in SPECS:
  state=empty_state();turns=[]
  for text,d in items:
   before=copy.deepcopy(state);state=apply(state,d)
   turns.append({'text':text,'before':before,'delta':d,'after':copy.deepcopy(state)})
  out.append({'id':name,'turns':turns})
 return out
